# Generated by Django 2.2.5 on 2019-12-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_dailycash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycash',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='dailycash',
            unique_together={('branch', 'date')},
        ),
    ]
